 name: Deploy to Heroku

 on:
   workflow_run:
     workflows: ["Node.js CI"]
     types: [completed]

 jobs:
   on-success:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_email: "sebastienleonce91@gmail.com"
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "quiet-wildwood-78539"

   on-failure:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'failure' }}
     steps:
       - run: echo "First workflow was a failure"
